/**
 * TypeScript interfaces for the AI Chat feature
 * Used for template creation/modification via natural language
 */

import type { AnyEmailComponent } from '@/types/plantilla'

// ============================================================================
// CHAT MESSAGE TYPES
// ============================================================================

/**
 * A single message in the chat conversation
 */
export interface ChatMessage {
  id: string
  role: 'user' | 'assistant'
  content: string
  template?: TemplatePreview | null
  timestamp: Date
  isStreaming?: boolean
}

/**
 * Preview of a template generated by the AI agent
 */
export interface TemplatePreview {
  nombre: string
  asunto: string
  componentes: AnyEmailComponent[]
}

// ============================================================================
// CHAT STATE
// ============================================================================

/**
 * State for the chat interface managed by useReducer
 */
export interface ChatState {
  messages: ChatMessage[]
  currentTemplate: TemplatePreview | null
  isStreaming: boolean
  isThinking: boolean
  conversationId: string | null
  error: string | null
}

/**
 * Actions for the chat reducer
 */
export type ChatAction =
  | { type: 'SET_THINKING'; payload: boolean }
  | { type: 'SET_STREAMING'; payload: boolean }
  | { type: 'ADD_USER_MESSAGE'; payload: { id: string; content: string } }
  | { type: 'ADD_ASSISTANT_MESSAGE'; payload: { id: string; content: string } }
  | { type: 'UPDATE_ASSISTANT_MESSAGE'; payload: { id: string; content: string } }
  | { type: 'SET_TEMPLATE'; payload: TemplatePreview | null }
  | { type: 'SET_MESSAGE_TEMPLATE'; payload: { id: string; template: TemplatePreview } }
  | { type: 'SET_CONVERSATION_ID'; payload: string }
  | { type: 'SET_ERROR'; payload: string | null }
  | { type: 'CLEAR_CONVERSATION' }
  | { type: 'RESTORE_HISTORY'; payload: { messages: ChatMessage[]; template: TemplatePreview | null; conversationId: string } }
  | { type: 'FINISH_STREAMING'; payload: { messageId: string } }

// ============================================================================
// SSE EVENTS
// ============================================================================

/**
 * Server-Sent Event types from the backend
 */
export type SSEEventType = 'thinking' | 'message' | 'template' | 'done' | 'error'

/**
 * Parsed SSE event from the backend
 */
export type SSEEvent =
  | { type: 'thinking'; content: string }
  | { type: 'message'; content: string }
  | { type: 'template'; content: TemplatePreview }
  | { type: 'done'; conversation_id: string }
  | { type: 'error'; content: string }

// ============================================================================
// API REQUEST/RESPONSE TYPES
// ============================================================================

/**
 * Request body for POST /api/plantilla-chat/message
 */
export interface SendMessageRequest {
  message: string
  conversation_id?: string
  existing_template_id?: number
}

/**
 * Request body for POST /api/plantilla-chat/save
 */
export interface SaveTemplateRequest {
  template: TemplatePreview
  nombre?: string
  descripcion?: string
  existing_id?: number
}

/**
 * Response from POST /api/plantilla-chat/save
 */
export interface SaveTemplateResponse {
  id: number
  mensaje: string
}

/**
 * Response from GET /api/plantilla-chat/history
 */
export interface ChatHistoryResponse {
  conversation_id: string
  messages: Array<{
    id: string
    role: 'user' | 'assistant'
    content: string
    template?: TemplatePreview | null
    timestamp: string
  }>
  current_template: TemplatePreview | null
}

// ============================================================================
// CALLBACK TYPES
// ============================================================================

/**
 * Callbacks for SSE event handling
 */
export interface SSECallbacks {
  onThinking?: (content: string) => void
  onMessage?: (content: string) => void
  onTemplate?: (template: TemplatePreview) => void
  onDone?: (conversationId: string) => void
  onError?: (error: string) => void
}
